apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-simple
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/Neelavati27/guestbook
      imageSelectionStrategy: SemVer
  - git:
      repoURL: https://github.com/Neelavati27/kargo-simple.git
      includePaths:
        - base
