apiVersion: v1
kind: Service
metadata:
  name: guestbook-simple
spec:
  type: NodePort
  selector:
    app: guestbook-simple
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30100
